// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBp8iZISYS5QLVvyAE7eYuJTDzeApX8lmo',
    appId: '1:788883148333:web:6cf13bbbb473628040b2a4',
    messagingSenderId: '788883148333',
    projectId: 'todo-c11-maadi',
    authDomain: 'todo-c11-maadi.firebaseapp.com',
    storageBucket: 'todo-c11-maadi.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB025r-ELJ04AR692CfHk8UKG2Um8KKJqA',
    appId: '1:788883148333:android:39b8bee08c76e47940b2a4',
    messagingSenderId: '788883148333',
    projectId: 'todo-c11-maadi',
    storageBucket: 'todo-c11-maadi.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB9p2pA5DkuyI7ONXAjb4Ign9yw99ESTgI',
    appId: '1:788883148333:ios:e184fe19038a66f940b2a4',
    messagingSenderId: '788883148333',
    projectId: 'todo-c11-maadi',
    storageBucket: 'todo-c11-maadi.appspot.com',
    iosBundleId: 'com.example.todoC11Maadi',
  );

}